---
- hosts: all
  user: ubuntu
  become: yes
  tasks: 
  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
      update_cache: yes
    become: yes

  - name: Update all packages to the latest version
    apt:
      name: "*"
      state: latest
    become: yes
  
  - name: Install required system packages
    apt: name={{ item }} state=latest update_cache=yes
    loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Update apt and install docker-ce
    apt: update_cache=yes name=docker-ce state=latest

  - name: Install Docker Module for Python
    pip:
      name: docker 
    
  - name: Docker group 
    command: "sudo usermod -aG docker ubuntu"

# - name: Ensure Nginx is at the latest version
#   apt:
#     name: nginx
#     state: latest
#   become: yes
#   
# - name: Make sure Nginx service is running
#   systemd:
#     state: started
#     name: nginx
#   become: yes

  