name: Push EC2
on:
  push:
   branches:
    - main

jobs:
  deploy:
    name: Deploy AWS
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout the files
      uses: actions/checkout@v3

    - name: Copy file with SSH
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{secrets.EC2_SSH_KEY}}
        SOURCE: "./"
        REMOTE_HOST: ${{secrets.HOSTNAME}}
        REMOTE_USER: ${{secrets.USER_NAME}}
        TARGET: "/home/ubuntu"

    - name: Executing remote ssh commands using key pair
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.HOSTNAME}}
        key: ${{secrets.EC2_SSH_KEY}}
        username: ${{secrets.USER_NAME}}
        port: 22
        script: |
            #Logged in ec2.
            cd ./Challenger/index
            docker-compose up --force-recreate --build -d
