name: Push EC2
on:
  push:
   branches:
    - main

jobs:
  deploy:
    name: Deploy AWS
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout the files
      uses: actions/checkout@v3

    - name: Copy file with SSH
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{secrets.EC2_SSH_KEY}}
        SOURCE: "./index"
        REMOTE_HOST: "34.204.9.228"
        REMOTE_USER: "ubuntu"
        TARGET: "/home/ubuntu"
