name: Push in ec2-prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy AWS
    runs-on: ubuntu:18.04

    steps:
    - name: Checkout files
      uses: actions/checkout@v3.1.0

    - name: ssh
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{secrets.EC2_SSH_KEY}}
        SOURCE: "./index"
        REMOTE_HOST: "34.204.9.228"
        REMOTE_USER: "ubuntu"
        TARGET: "/home/ubuntu"
